{% set name = "backrefs" %}
{% set version = "5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backrefs-{{ version }}.tar.gz
  sha256: 5a99074a38c59aaca0b30da54ce714ae06263b6a544f2278483ceb42933dc529

build:
  number: 0
  skip: true  # [py<=34]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - backrefs
    - backrefs.uniprops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facelessuser/backrefs
  summary: A wrapper around re and regex that adds additional back references.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
