{% set name = "backrefs" %}
{% set version = "5.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backrefs-{{ version }}.tar.gz
  sha256: b66bd67bc715379915c76e70212a9fb71ff17b51a561ce49e717db5e80db2db2

build:
  noarch: python
  number: 0
  skip: true  # [py<=34]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - backrefs
    - backrefs.uniprops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facelessuser/backrefs
  summary: A wrapper around re and regex that adds additional back references.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
