{% set name = "backrefs" %}
{% set version = "5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backrefs-{{ version }}.tar.gz
  sha256: 4659500cf46e0b82661516d898eb154233791373af7a03fe553c17abf28315d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python  >=3.6
  run:
    - python  >=3.6

test:
  imports:
    - backrefs
    - backrefs.uniprops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facelessuser/backrefs
  summary: A wrapper around re and regex that adds additional back references.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
