{% set name = "backrefs" %}
{% set version = "6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/backrefs-{{ version }}.tar.gz
  sha256: f44ff4d48808b243b6c0cdc6231e22195c32f77046018141556c66f8bab72a49

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=0.21.1
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - backrefs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facelessuser/backrefs
  summary: A wrapper around re and regex that adds additional back references.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
    - thewchan
