{% set name = "backrefs" %}
{% set version = "4.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backrefs-{{ version }}.tar.gz
  sha256: c6ede024bcbbf5a3fc42c27a8ca2e1e962ad1f7073f611fffdf3a3932a812ab0

build:
  number: 0
  skip: true  # [py<=34]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - backrefs
    - backrefs.uniprops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facelessuser/backrefs
  summary: A wrapper around re and regex that adds additional back references.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
